version: '3.1'
services:

  stats-service:
    build: stat-service/server
    image: stats-service-image
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=stats-db-user
      - SPRING_DATASOURCE_PASSWORD=stats-db-password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats-db-user
      - POSTGRES_PASSWORD=stats-db-password

  main-service:
    build: main-service
    image: main-server-image
    container_name: main-server-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=main-db-user
      - SPRING_DATASOURCE_PASSWORD=main-db-password

  main-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=main-db-user
      - POSTGRES_PASSWORD=main-db-password
